define(['./lang/clone', './lang/cloneDeep', './lang/eq', './lang/gt', './lang/gte', './lang/isArguments', './lang/isArray', './lang/isBoolean', './lang/isDate', './lang/isElement', './lang/isEmpty', './lang/isEqual', './lang/isError', './lang/isFinite', './lang/isFunction', './lang/isMatch', './lang/isNaN', './lang/isNative', './lang/isNull', './lang/isNumber', './lang/isObject', './lang/isPlainObject', './lang/isRegExp', './lang/isString', './lang/isTypedArray', './lang/isUndefined', './lang/lt', './lang/lte', './lang/toArray', './lang/toPlainObject'], function(clone, cloneDeep, eq, gt, gte, isArguments, isArray, isBoolean, isDate, isElement, isEmpty, isEqual, isError, isFinite, isFunction, isMatch, isNaN, isNative, isNull, isNumber, isObject, isPlainObject, isRegExp, isString, isTypedArray, isUndefined, lt, lte, toArray, toPlainObject) {
  return {
    'clone': clone,
    'cloneDeep': cloneDeep,
    'eq': eq,
    'gt': gt,
    'gte': gte,
    'isArguments': isArguments,
    'isArray': isArray,
    'isBoolean': isBoolean,
    'isDate': isDate,
    'isElement': isElement,
    'isEmpty': isEmpty,
    'isEqual': isEqual,
    'isError': isError,
    'isFinite': isFinite,
    'isFunction': isFunction,
    'isMatch': isMatch,
    'isNaN': isNaN,
    'isNative': isNative,
    'isNull': isNull,
    'isNumber': isNumber,
    'isObject': isObject,
    'isPlainObject': isPlainObject,
    'isRegExp': isRegExp,
    'isString': isString,
    'isTypedArray': isTypedArray,
    'isUndefined': isUndefined,
    'lt': lt,
    'lte': lte,
    'toArray': toArray,
    'toPlainObject': toPlainObject
  };
});
