define(['./camelCase', './capitalize', './deburr', './endsWith', './escape', './escapeRegExp', './kebabCase', './lowerCase', './lowerFirst', './pad', './padEnd', './padStart', './parseInt', './repeat', './replace', './snakeCase', './split', './startCase', './startsWith', './template', './templateSettings', './toLower', './toUpper', './trim', './trimEnd', './trimStart', './truncate', './unescape', './upperCase', './upperFirst', './words'], function(camelCase, capitalize, deburr, endsWith, escape, escapeRegExp, kebabCase, lowerCase, lowerFirst, pad, padEnd, padStart, parseInt, repeat, replace, snakeCase, split, startCase, startsWith, template, templateSettings, toLower, toUpper, trim, trimEnd, trimStart, truncate, unescape, upperCase, upperFirst, words) {
  return {
    'camelCase': camelCase,
    'capitalize': capitalize,
    'deburr': deburr,
    'endsWith': endsWith,
    'escape': escape,
    'escapeRegExp': escapeRegExp,
    'kebabCase': kebabCase,
    'lowerCase': lowerCase,
    'lowerFirst': lowerFirst,
    'pad': pad,
    'padEnd': padEnd,
    'padStart': padStart,
    'parseInt': parseInt,
    'repeat': repeat,
    'replace': replace,
    'snakeCase': snakeCase,
    'split': split,
    'startCase': startCase,
    'startsWith': startsWith,
    'template': template,
    'templateSettings': templateSettings,
    'toLower': toLower,
    'toUpper': toUpper,
    'trim': trim,
    'trimEnd': trimEnd,
    'trimStart': trimStart,
    'truncate': truncate,
    'unescape': unescape,
    'upperCase': upperCase,
    'upperFirst': upperFirst,
    'words': words
  };
});
