define(['./attempt', './bindAll', './cond', './conforms', './constant', './defaultTo', './flow', './flowRight', './identity', './iteratee', './matches', './matchesProperty', './method', './methodOf', './mixin', './noop', './nthArg', './over', './overEvery', './overSome', './property', './propertyOf', './range', './rangeRight', './stubArray', './stubFalse', './stubObject', './stubString', './stubTrue', './times', './toPath', './uniqueId'], function(attempt, bindAll, cond, conforms, constant, defaultTo, flow, flowRight, identity, iteratee, matches, matchesProperty, method, methodOf, mixin, noop, nthArg, over, overEvery, overSome, property, propertyOf, range, rangeRight, stubArray, stubFalse, stubObject, stubString, stubTrue, times, toPath, uniqueId) {
  return {
    'attempt': attempt,
    'bindAll': bindAll,
    'cond': cond,
    'conforms': conforms,
    'constant': constant,
    'defaultTo': defaultTo,
    'flow': flow,
    'flowRight': flowRight,
    'identity': identity,
    'iteratee': iteratee,
    'matches': matches,
    'matchesProperty': matchesProperty,
    'method': method,
    'methodOf': methodOf,
    'mixin': mixin,
    'noop': noop,
    'nthArg': nthArg,
    'over': over,
    'overEvery': overEvery,
    'overSome': overSome,
    'property': property,
    'propertyOf': propertyOf,
    'range': range,
    'rangeRight': rangeRight,
    'stubArray': stubArray,
    'stubFalse': stubFalse,
    'stubObject': stubObject,
    'stubString': stubString,
    'stubTrue': stubTrue,
    'times': times,
    'toPath': toPath,
    'uniqueId': uniqueId
  };
});
