name: CI Bun

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Bun CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bun-version: [1.0.0, 1.1.0, 1.2.0, 1.3.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      # TODO: Remove this step once the lockfile has been updated to v3 in the repository
      - name: Install npm dependencies (lockfile v3)
        run: npm i --lockfile-version 3 --package-lock-only

      - name: Install dependencies
        run: bun install

      - name: Run validate
        run: bun run validate