name: CI Bun

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Bun CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bun-version: [1.0.0, 1.1.0, 1.2.0, 1.3.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: ${{ matrix.bun-version }}

      # TODO: Remove this step once the lockfile has been updated to v3 in the repository
      - name: Install npm dependencies (lockfile v3)
        run: npm i --lockfile-version 3 --package-lock-only

      - name: Install dependencies
        run: bun install

      - name: Run validate
        run: bun run validate
